### ISSUE TITLE
Image Loading a bit slower

### ISSUE THREAD

**Issue by crypto-navdeep** [Ved-programmer/ved-programmer.github.io#43]
Hi Ved, 

The Lazy Load Images are showing up a bit latter, as you may already be aware of, some time they are also loading up at irregular times, at one time, you're metrics loaded a bit faster then the stats and some times, you metrics were loading for almost 2 seconds.

Well There is a solution, instead of show-up effect, it would be better we you would add slide-in effects, like the one in my website. Hope you could do it : ) there are many libraries to help you with this work.

Regards,
Navdeep K.

**Comment by Ved-programmer** [comment]
I see. I will look into it, I am keeping this issue open

**Comment by Ved-programmer** [comment]
Well, I don't think the slide in effect is going to look very good and so I am going to remove the lazy loading itself.

**Comment by crypto-navdeep** [comment]
LGTM! 👀
